#!/bin/bash

docker pull ghcr.io/dbt-labs/dbt-redshift:latest

docker run \
--name cmmc \
--rm \
--network=host \
--mount type=bind,source=./cmmc/,target=/usr/app \
--mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml \
ghcr.io/dbt-labs/dbt-redshift:latest \
ls

echo 'Doc string blabla'

echo '
alias dbt-run="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt run"
alias dbt-test="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt test"
alias dbt-build="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt build"
alias dbt-clean="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt clean"
alias dbt-clone="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt clone"
alias dbt-compile="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt compile"
alias dbt-debug="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt debug"
alias dbt-deps="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt deps"
alias dbt-docs="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt docs"
alias dbt-list="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt list"
alias dbt-parse="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt parse"
alias dbt-retry="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt retry"
alias dbt-run-operation="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt run-operation"
alias dbt-seed="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt seed"
alias dbt-show="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt show"
alias dbt-snapshot="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt snapshot"
alias dbt-snapshot="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt snapshot"
alias dbt-source="docker run --name cmmc --rm --network=host --mount type=bind,source=./cmmc/,target=/usr/app --mount type=bind,source=$(pwd)/cmmc/profiles.yml,target=/root/.dbt/profiles.yml ghcr.io/dbt-labs/dbt-redshift:latest dbt source"
' >> ~/.bashrc

source ~/.bashrc
