name: "CD for MWAA"
on:
  push:
    branches:
      - test
      - feature/TDET-81-silver-dag-test
env:
  AWS_REGION_NAME: ${{ vars.AWS_REGION_NAME }}
  AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION_NAME }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
      - name: Create a ZIP of the plugins directory
        run: |
          cd plugins
          zip -r ../plugins.zip *
      - name: Sync Airflow files to the MWAA S3 bucket with the AWS CLI
        run: |
          aws s3 sync . s3://${{ env.AWS_BUCKET_NAME }} --follow-symlinks --delete \
          --exclude '*' \
          --include 'dags/*' \
          --include 'plugins.zip' \
          --include 'requirements.txt' \
          --exclude '*.pyc'
